#!/usr/bin/env bash

CLAMSHELL=$(ioreg -r -k AppleClamshellState | grep AppleClamshellState | grep Yes)
MUTEX=$TMPDIR/clamdown.is.sleeping

if [ "$CLAMSHELL" ]; then
    if [[ ! -f $MUTEX ]]; then
        touch $MUTEX
        pmset sleepnow
    fi
else
  rm -f $MUTEX    
fi